project:
  type: website

website:
  title: "The Webbiest Site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: project.qmd
        text: Projects
      - href: coolthings.qmd
        text: Cool things
      - about.qmd

format:
  html:
    theme:
      - litera
      - brand
    css: styles.css
    toc: true



